### PR TITLE
Update apr 2022

### PR DESCRIPTION
**Pull request by maehr**
Add / Remove / Edit {entry name} to/from the "{section name}" section.

**Short pitch**

Describe why this change is made. Alternatively, refer to existing issues if
any. You could try to answer:

- Why do / don't you find this tool awesome?
- How do you use this tool in your workflow?
- What advantages / disadvantages does it have compared to {another tool}?

## Checklist

- [ ] I have read and understood the [contribution guidelines](https://github.com/writing-resources/awesome-scientific-writing/blob/main/CONTRIBUTING.md).
- [ ] Table of contents has been updated (if a section is added / removed).
- [ ] Contents have been sorted alphabetically.

### CODE REVIEW

**Review by diegosiqueir4 — APPROVED** [review]

**Review by diegosiqueir4 — APPROVED** [review]
All links have descriptions and are in accordance with the guidelines. Thanks!

**Comment by maehr** [comment]
@diegosiqueir4 Thanks! 
PS: If you are interested in co-maintaining this list as well, let me know.

**Comment by diegosiqueir4** [comment]
> @diegosiqueir4 Thanks! PS: If you are interested in co-maintaining this list as well, let me know.

To be honest with you, I thought I was reviewing a PR from dh-tech/awesome-dhtools :sweat_smile:. But of course, if I can help, I will gladly do so (notifications for your repository are already activated :muscle:)

**Comment by maehr** [comment]
> > @diegosiqueir4 Thanks! PS: If you are interested in co-maintaining this list as well, let me know.
> 
> To be honest with you, I thought I was reviewing a PR from dh-tech/awesome-dhtools :sweat_smile:. But of course, if I can help, I will gladly do so (notifications for your repository are already activated :muscle:)

I suspected that 😇 At the moment there's not much going on apart from my monthly updates. Adding you as a mainteiner forces me to think about the criteria of relevance for the list entries... I will keep you posted as soon as I come up with ideas.

**Pull request merged**
