### PR TITLE
 update README.md with Brazil section 

### PR DESCRIPTION
**Pull request by geraldohomero**
I'm just contributing to the addition of a section referring to Brazil and its works in digital history

## Checklist

- [x] I have read and understood the [contribution guidelines](https://github.com/writing-resources/awesome-scientific-writing/blob/main/CONTRIBUTING.md).
- [x] Table of contents has been updated (if a section is added / removed).
- [x] Contents have been sorted alphabetically.

with changes

### CODE REVIEW

**Comment by maehr** [comment]
@geraldohomero thanks again and please incorporate all the feedback from https://github.com/maehr/awesome-digital-history/pull/40

**Comment by maehr** [comment]
@geraldohomero can you please answer the following questions for the additions to the list. For people not understanding Portuguese this would be very helpful.

> Short pitch
> 
> Describe why this change is made. Alternatively, refer to existing issues if
> any. You could try to answer:
> 
> Why do / don't you find this tool awesome?
> How do you use this tool in your workflow?
> What advantages / disadvantages does it have compared to {another tool}?

**Comment by geraldohomero** [comment]
This change was mainly made considering the lack of a Brazil section in this tool. I'm trying to contribute so that more people can see the work done by Brazilians in the field of digital history. I believe that not only Brazilians can benefit from this addition, since there are many researchers with themes that permeate Brazil directly or indirectly. 
So, I see it as a way to show researchers or the curious about Brazilian digital history.

**Comment by maehr** [comment]
> This change was mainly made considering the lack of a Brazil section in this tool. I'm trying to contribute so that more people can see the work done by Brazilians in the field of digital history. I believe that not only Brazilians can benefit from this addition, since there are many researchers with themes that permeate Brazil directly or indirectly. So, I see it as a way to show researchers or the curious about Brazilian digital history.

Thank you very much for your quick reply. I absolutely agree with adding Brazilian resources. I was just curious about the content of the archive. Can you describe them for people who don't speak Portuguese?

**Comment by geraldohomero** [comment]
"Hemeroteca Digital" offers access to the national periodicals portal that provides wide consultation, through the internet, of its collection of periodicals – newspapers, magazines, yearbooks, bulletins, etc. – and serial publications. The oldest periodicals in the digital collection date from the beginning of the 19th century, such as "Correio Braziliense" and "Gazeta do Rio de Janeiro", both founded in 1808 - to newspapers extinct in the 20th century, such as "Diário Carioca" and " Correio da Manhã", or that no longer circulate in printed form, as in the case of "Jornal do Brasil". Is the largest virtual collection of national periodicals and can be accessed free of charge worldwide.
The collection can be consulted by title, period, edition, place of publication and word(s). The search for words is possible due to the use of Optical Character Recognition (OCR) technology, which provides researchers with greater reach in textual research in journals.

"História da Ditadura" provides documents related to the context of the military dictatorship (1964-1985) in Brazil. Documents such as: minutes of film censorship processes, plays, musical events, etc. In addition to documents from the "National Information Service" (Serviço Nacional de Informação/SNI), with registration forms for political prisoners and minutes referring to the "political disappearances" by the dictatorship.
According to the project's website: "História da Ditadura will share historical documents selected by the site's columnists with brief analytical comments. The objective is to expand access to historical knowledge, documentary collections and historiographical production."

**Comment by maehr** [comment]
> "Hemeroteca Digital" offers access to the national periodicals portal that provides wide consultation, through the internet, of its collection of periodicals – newspapers, magazines, yearbooks, bulletins, etc. – and serial publications. The oldest periodicals in the digital collection date from the beginning of the 19th century, such as "Correio Braziliense" and "Gazeta do Rio de Janeiro", both founded in 1808 - to newspapers extinct in the 20th century, such as "Diário Carioca" and " Correio da Manhã", or that no longer circulate in printed form, as in the case of "Jornal do Brasil". Is the largest virtual collection of national periodicals and can be accessed free of charge worldwide. The collection can be consulted by title, period, edition, place of publication and word(s). The search for words is possible due to the use of Optical Character Recognition (OCR) technology, which provides researchers with greater reach in textual research in journals.
> 
> "História da Ditadura" provides documents related to the context of the military dictatorship (1964-1985) in Brazil. Documents such as: minutes of film censorship processes, plays, musical events, etc. In addition to documents from the "National Information Service" (Serviço Nacional de Informação/SNI), with registration forms for political prisoners and minutes referring to the "political disappearances" by the dictatorship. According to the project's website: "História da Ditadura will share historical documents selected by the site's columnists with brief analytical comments. The objective is to expand access to historical knowledge, documentary collections and historiographical production."

Hi @geraldohomero 
I am very sorry for not having answered sooner. We are still in the process of figuring out what the scope of this list is going to be. We won't have a clearcut answer before November. But I am pretty sure that <https://www.historiadaditadura.com.br/documentosdadiradura> won't make the cut. INHO it's not a repository with primary sources for historians that want to do research.

**Pull request closed without merging**
